//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1.JS_Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JS_Service.Service1Soap")]
    public interface Service1Soap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.HelloWorldResponse HelloWorld(WindowsFormsApplication1.JS_Service.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/addition", ReplyAction="*")]
        double addition(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/subtract", ReplyAction="*")]
        double subtract(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/multiplication", ReplyAction="*")]
        double multiplication(double i, double j);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/division", ReplyAction="*")]
        double division(double i, double j);
        
        // CODEGEN: Generating message contract since element name Region from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnDevice_SN_Info", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoResponse ReturnDevice_SN_Info(WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoRequest request);
        
        // CODEGEN: Generating message contract since element name Reporter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CollectDevice_MES_TPMData_New", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewResponse CollectDevice_MES_TPMData_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewRequest request);
        
        // CODEGEN: Generating message contract since element name Reporter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CollectDevice_MES_StartJob_New", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewResponse CollectDevice_MES_StartJob_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewRequest request);
        
        // CODEGEN: Generating message contract since element name Reporter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CollectDevice_MES_ControlJob_New", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewResponse CollectDevice_MES_ControlJob_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewRequest request);
        
        // CODEGEN: Generating message contract since element name Reporter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CollectDevice_MES_ProcessData_New", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewResponse CollectDevice_MES_ProcessData_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewRequest request);
        
        // CODEGEN: Generating message contract since element name Reporter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CollectDevice_MES_EndJob_New", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewResponse CollectDevice_MES_EndJob_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewRequest request);
        
        // CODEGEN: Generating message contract since element name Reporter from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CollectDevice_MES_Doc_New", ReplyAction="*")]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewResponse CollectDevice_MES_Doc_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(WindowsFormsApplication1.JS_Service.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(WindowsFormsApplication1.JS_Service.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnDevice_SN_InfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnDevice_SN_Info", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoRequestBody Body;
        
        public ReturnDevice_SN_InfoRequest() {
        }
        
        public ReturnDevice_SN_InfoRequest(WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnDevice_SN_InfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Region;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string ProductSN;
        
        public ReturnDevice_SN_InfoRequestBody() {
        }
        
        public ReturnDevice_SN_InfoRequestBody(string Region, string ProductSN) {
            this.Region = Region;
            this.ProductSN = ProductSN;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnDevice_SN_InfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnDevice_SN_InfoResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoResponseBody Body;
        
        public ReturnDevice_SN_InfoResponse() {
        }
        
        public ReturnDevice_SN_InfoResponse(WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnDevice_SN_InfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReturnDevice_SN_InfoResult;
        
        public ReturnDevice_SN_InfoResponseBody() {
        }
        
        public ReturnDevice_SN_InfoResponseBody(string ReturnDevice_SN_InfoResult) {
            this.ReturnDevice_SN_InfoResult = ReturnDevice_SN_InfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_TPMData_NewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_TPMData_New", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewRequestBody Body;
        
        public CollectDevice_MES_TPMData_NewRequest() {
        }
        
        public CollectDevice_MES_TPMData_NewRequest(WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_TPMData_NewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Reporter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProblemType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Ext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string InputTime;
        
        public CollectDevice_MES_TPMData_NewRequestBody() {
        }
        
        public CollectDevice_MES_TPMData_NewRequestBody(string Reporter, string DeviceCode, string ProblemType, string Ext, string InputTime) {
            this.Reporter = Reporter;
            this.DeviceCode = DeviceCode;
            this.ProblemType = ProblemType;
            this.Ext = Ext;
            this.InputTime = InputTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_TPMData_NewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_TPMData_NewResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewResponseBody Body;
        
        public CollectDevice_MES_TPMData_NewResponse() {
        }
        
        public CollectDevice_MES_TPMData_NewResponse(WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_TPMData_NewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CollectDevice_MES_TPMData_NewResult;
        
        public CollectDevice_MES_TPMData_NewResponseBody() {
        }
        
        public CollectDevice_MES_TPMData_NewResponseBody(string CollectDevice_MES_TPMData_NewResult) {
            this.CollectDevice_MES_TPMData_NewResult = CollectDevice_MES_TPMData_NewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_StartJob_NewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_StartJob_New", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewRequestBody Body;
        
        public CollectDevice_MES_StartJob_NewRequest() {
        }
        
        public CollectDevice_MES_StartJob_NewRequest(WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_StartJob_NewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Reporter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OperationGroup;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string InputTime;
        
        public CollectDevice_MES_StartJob_NewRequestBody() {
        }
        
        public CollectDevice_MES_StartJob_NewRequestBody(string Reporter, string DeviceCode, string ProductType, string ProductSN, string OperationGroup, string Ext, string InputTime) {
            this.Reporter = Reporter;
            this.DeviceCode = DeviceCode;
            this.ProductType = ProductType;
            this.ProductSN = ProductSN;
            this.OperationGroup = OperationGroup;
            this.Ext = Ext;
            this.InputTime = InputTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_StartJob_NewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_StartJob_NewResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewResponseBody Body;
        
        public CollectDevice_MES_StartJob_NewResponse() {
        }
        
        public CollectDevice_MES_StartJob_NewResponse(WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_StartJob_NewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CollectDevice_MES_StartJob_NewResult;
        
        public CollectDevice_MES_StartJob_NewResponseBody() {
        }
        
        public CollectDevice_MES_StartJob_NewResponseBody(string CollectDevice_MES_StartJob_NewResult) {
            this.CollectDevice_MES_StartJob_NewResult = CollectDevice_MES_StartJob_NewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_ControlJob_NewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_ControlJob_New", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewRequestBody Body;
        
        public CollectDevice_MES_ControlJob_NewRequest() {
        }
        
        public CollectDevice_MES_ControlJob_NewRequest(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_ControlJob_NewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Reporter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OperationGroup;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string ControlKey;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string InputTime;
        
        public CollectDevice_MES_ControlJob_NewRequestBody() {
        }
        
        public CollectDevice_MES_ControlJob_NewRequestBody(string Reporter, string DeviceCode, string ProductType, string ProductSN, string OperationGroup, string Ext, string ControlKey, string InputTime) {
            this.Reporter = Reporter;
            this.DeviceCode = DeviceCode;
            this.ProductType = ProductType;
            this.ProductSN = ProductSN;
            this.OperationGroup = OperationGroup;
            this.Ext = Ext;
            this.ControlKey = ControlKey;
            this.InputTime = InputTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_ControlJob_NewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_ControlJob_NewResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewResponseBody Body;
        
        public CollectDevice_MES_ControlJob_NewResponse() {
        }
        
        public CollectDevice_MES_ControlJob_NewResponse(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_ControlJob_NewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CollectDevice_MES_ControlJob_NewResult;
        
        public CollectDevice_MES_ControlJob_NewResponseBody() {
        }
        
        public CollectDevice_MES_ControlJob_NewResponseBody(string CollectDevice_MES_ControlJob_NewResult) {
            this.CollectDevice_MES_ControlJob_NewResult = CollectDevice_MES_ControlJob_NewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_ProcessData_NewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_ProcessData_New", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewRequestBody Body;
        
        public CollectDevice_MES_ProcessData_NewRequest() {
        }
        
        public CollectDevice_MES_ProcessData_NewRequest(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_ProcessData_NewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Reporter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string PropertyName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string PropertyValue;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string Ext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string InputTime;
        
        public CollectDevice_MES_ProcessData_NewRequestBody() {
        }
        
        public CollectDevice_MES_ProcessData_NewRequestBody(string Reporter, string DeviceCode, string ProductType, string ProductSN, string PropertyName, string PropertyValue, string Ext, string InputTime) {
            this.Reporter = Reporter;
            this.DeviceCode = DeviceCode;
            this.ProductType = ProductType;
            this.ProductSN = ProductSN;
            this.PropertyName = PropertyName;
            this.PropertyValue = PropertyValue;
            this.Ext = Ext;
            this.InputTime = InputTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_ProcessData_NewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_ProcessData_NewResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewResponseBody Body;
        
        public CollectDevice_MES_ProcessData_NewResponse() {
        }
        
        public CollectDevice_MES_ProcessData_NewResponse(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_ProcessData_NewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CollectDevice_MES_ProcessData_NewResult;
        
        public CollectDevice_MES_ProcessData_NewResponseBody() {
        }
        
        public CollectDevice_MES_ProcessData_NewResponseBody(string CollectDevice_MES_ProcessData_NewResult) {
            this.CollectDevice_MES_ProcessData_NewResult = CollectDevice_MES_ProcessData_NewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_EndJob_NewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_EndJob_New", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewRequestBody Body;
        
        public CollectDevice_MES_EndJob_NewRequest() {
        }
        
        public CollectDevice_MES_EndJob_NewRequest(WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_EndJob_NewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Reporter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string OperationGroup;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Ext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string InputTime;
        
        public CollectDevice_MES_EndJob_NewRequestBody() {
        }
        
        public CollectDevice_MES_EndJob_NewRequestBody(string Reporter, string DeviceCode, string ProductType, string ProductSN, string OperationGroup, string Ext, string InputTime) {
            this.Reporter = Reporter;
            this.DeviceCode = DeviceCode;
            this.ProductType = ProductType;
            this.ProductSN = ProductSN;
            this.OperationGroup = OperationGroup;
            this.Ext = Ext;
            this.InputTime = InputTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_EndJob_NewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_EndJob_NewResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewResponseBody Body;
        
        public CollectDevice_MES_EndJob_NewResponse() {
        }
        
        public CollectDevice_MES_EndJob_NewResponse(WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_EndJob_NewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CollectDevice_MES_EndJob_NewResult;
        
        public CollectDevice_MES_EndJob_NewResponseBody() {
        }
        
        public CollectDevice_MES_EndJob_NewResponseBody(string CollectDevice_MES_EndJob_NewResult) {
            this.CollectDevice_MES_EndJob_NewResult = CollectDevice_MES_EndJob_NewResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_Doc_NewRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_Doc_New", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewRequestBody Body;
        
        public CollectDevice_MES_Doc_NewRequest() {
        }
        
        public CollectDevice_MES_Doc_NewRequest(WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_Doc_NewRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Reporter;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string DeviceCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ProductType;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string ProductSN;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string DocType;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int FolderID;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string FileName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public byte[] Content;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string Ext;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string InputTime;
        
        public CollectDevice_MES_Doc_NewRequestBody() {
        }
        
        public CollectDevice_MES_Doc_NewRequestBody(string Reporter, string DeviceCode, string ProductType, string ProductSN, string DocType, int FolderID, string FileName, byte[] Content, string Ext, string InputTime) {
            this.Reporter = Reporter;
            this.DeviceCode = DeviceCode;
            this.ProductType = ProductType;
            this.ProductSN = ProductSN;
            this.DocType = DocType;
            this.FolderID = FolderID;
            this.FileName = FileName;
            this.Content = Content;
            this.Ext = Ext;
            this.InputTime = InputTime;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CollectDevice_MES_Doc_NewResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CollectDevice_MES_Doc_NewResponse", Namespace="http://tempuri.org/", Order=0)]
        public WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewResponseBody Body;
        
        public CollectDevice_MES_Doc_NewResponse() {
        }
        
        public CollectDevice_MES_Doc_NewResponse(WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CollectDevice_MES_Doc_NewResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CollectDevice_MES_Doc_NewResult;
        
        public CollectDevice_MES_Doc_NewResponseBody() {
        }
        
        public CollectDevice_MES_Doc_NewResponseBody(string CollectDevice_MES_Doc_NewResult) {
            this.CollectDevice_MES_Doc_NewResult = CollectDevice_MES_Doc_NewResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : WindowsFormsApplication1.JS_Service.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<WindowsFormsApplication1.JS_Service.Service1Soap>, WindowsFormsApplication1.JS_Service.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.HelloWorldResponse WindowsFormsApplication1.JS_Service.Service1Soap.HelloWorld(WindowsFormsApplication1.JS_Service.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            WindowsFormsApplication1.JS_Service.HelloWorldRequest inValue = new WindowsFormsApplication1.JS_Service.HelloWorldRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.HelloWorldRequestBody();
            WindowsFormsApplication1.JS_Service.HelloWorldResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        public double addition(double i, double j) {
            return base.Channel.addition(i, j);
        }
        
        public double subtract(double i, double j) {
            return base.Channel.subtract(i, j);
        }
        
        public double multiplication(double i, double j) {
            return base.Channel.multiplication(i, j);
        }
        
        public double division(double i, double j) {
            return base.Channel.division(i, j);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoResponse WindowsFormsApplication1.JS_Service.Service1Soap.ReturnDevice_SN_Info(WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoRequest request) {
            return base.Channel.ReturnDevice_SN_Info(request);
        }
        
        public string ReturnDevice_SN_Info(string Region, string ProductSN) {
            WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoRequest inValue = new WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoRequestBody();
            inValue.Body.Region = Region;
            inValue.Body.ProductSN = ProductSN;
            WindowsFormsApplication1.JS_Service.ReturnDevice_SN_InfoResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).ReturnDevice_SN_Info(inValue);
            return retVal.Body.ReturnDevice_SN_InfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewResponse WindowsFormsApplication1.JS_Service.Service1Soap.CollectDevice_MES_TPMData_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewRequest request) {
            return base.Channel.CollectDevice_MES_TPMData_New(request);
        }
        
        public string CollectDevice_MES_TPMData_New(string Reporter, string DeviceCode, string ProblemType, string Ext, string InputTime) {
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewRequest inValue = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewRequestBody();
            inValue.Body.Reporter = Reporter;
            inValue.Body.DeviceCode = DeviceCode;
            inValue.Body.ProblemType = ProblemType;
            inValue.Body.Ext = Ext;
            inValue.Body.InputTime = InputTime;
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_TPMData_NewResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).CollectDevice_MES_TPMData_New(inValue);
            return retVal.Body.CollectDevice_MES_TPMData_NewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewResponse WindowsFormsApplication1.JS_Service.Service1Soap.CollectDevice_MES_StartJob_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewRequest request) {
            return base.Channel.CollectDevice_MES_StartJob_New(request);
        }
        
        public string CollectDevice_MES_StartJob_New(string Reporter, string DeviceCode, string ProductType, string ProductSN, string OperationGroup, string Ext, string InputTime) {
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewRequest inValue = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewRequestBody();
            inValue.Body.Reporter = Reporter;
            inValue.Body.DeviceCode = DeviceCode;
            inValue.Body.ProductType = ProductType;
            inValue.Body.ProductSN = ProductSN;
            inValue.Body.OperationGroup = OperationGroup;
            inValue.Body.Ext = Ext;
            inValue.Body.InputTime = InputTime;
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_StartJob_NewResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).CollectDevice_MES_StartJob_New(inValue);
            return retVal.Body.CollectDevice_MES_StartJob_NewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewResponse WindowsFormsApplication1.JS_Service.Service1Soap.CollectDevice_MES_ControlJob_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewRequest request) {
            return base.Channel.CollectDevice_MES_ControlJob_New(request);
        }
        
        public string CollectDevice_MES_ControlJob_New(string Reporter, string DeviceCode, string ProductType, string ProductSN, string OperationGroup, string Ext, string ControlKey, string InputTime) {
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewRequest inValue = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewRequestBody();
            inValue.Body.Reporter = Reporter;
            inValue.Body.DeviceCode = DeviceCode;
            inValue.Body.ProductType = ProductType;
            inValue.Body.ProductSN = ProductSN;
            inValue.Body.OperationGroup = OperationGroup;
            inValue.Body.Ext = Ext;
            inValue.Body.ControlKey = ControlKey;
            inValue.Body.InputTime = InputTime;
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_ControlJob_NewResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).CollectDevice_MES_ControlJob_New(inValue);
            return retVal.Body.CollectDevice_MES_ControlJob_NewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewResponse WindowsFormsApplication1.JS_Service.Service1Soap.CollectDevice_MES_ProcessData_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewRequest request) {
            return base.Channel.CollectDevice_MES_ProcessData_New(request);
        }
        
        public string CollectDevice_MES_ProcessData_New(string Reporter, string DeviceCode, string ProductType, string ProductSN, string PropertyName, string PropertyValue, string Ext, string InputTime) {
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewRequest inValue = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewRequestBody();
            inValue.Body.Reporter = Reporter;
            inValue.Body.DeviceCode = DeviceCode;
            inValue.Body.ProductType = ProductType;
            inValue.Body.ProductSN = ProductSN;
            inValue.Body.PropertyName = PropertyName;
            inValue.Body.PropertyValue = PropertyValue;
            inValue.Body.Ext = Ext;
            inValue.Body.InputTime = InputTime;
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_ProcessData_NewResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).CollectDevice_MES_ProcessData_New(inValue);
            return retVal.Body.CollectDevice_MES_ProcessData_NewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewResponse WindowsFormsApplication1.JS_Service.Service1Soap.CollectDevice_MES_EndJob_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewRequest request) {
            return base.Channel.CollectDevice_MES_EndJob_New(request);
        }
        
        public string CollectDevice_MES_EndJob_New(string Reporter, string DeviceCode, string ProductType, string ProductSN, string OperationGroup, string Ext, string InputTime) {
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewRequest inValue = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewRequestBody();
            inValue.Body.Reporter = Reporter;
            inValue.Body.DeviceCode = DeviceCode;
            inValue.Body.ProductType = ProductType;
            inValue.Body.ProductSN = ProductSN;
            inValue.Body.OperationGroup = OperationGroup;
            inValue.Body.Ext = Ext;
            inValue.Body.InputTime = InputTime;
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_EndJob_NewResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).CollectDevice_MES_EndJob_New(inValue);
            return retVal.Body.CollectDevice_MES_EndJob_NewResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewResponse WindowsFormsApplication1.JS_Service.Service1Soap.CollectDevice_MES_Doc_New(WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewRequest request) {
            return base.Channel.CollectDevice_MES_Doc_New(request);
        }
        
        public string CollectDevice_MES_Doc_New(string Reporter, string DeviceCode, string ProductType, string ProductSN, string DocType, int FolderID, string FileName, byte[] Content, string Ext, string InputTime) {
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewRequest inValue = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewRequest();
            inValue.Body = new WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewRequestBody();
            inValue.Body.Reporter = Reporter;
            inValue.Body.DeviceCode = DeviceCode;
            inValue.Body.ProductType = ProductType;
            inValue.Body.ProductSN = ProductSN;
            inValue.Body.DocType = DocType;
            inValue.Body.FolderID = FolderID;
            inValue.Body.FileName = FileName;
            inValue.Body.Content = Content;
            inValue.Body.Ext = Ext;
            inValue.Body.InputTime = InputTime;
            WindowsFormsApplication1.JS_Service.CollectDevice_MES_Doc_NewResponse retVal = ((WindowsFormsApplication1.JS_Service.Service1Soap)(this)).CollectDevice_MES_Doc_New(inValue);
            return retVal.Body.CollectDevice_MES_Doc_NewResult;
        }
    }
}
